# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-nix-21-05:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

  build-nix-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

  run-make-all:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          with:
            clean: false
      - name: Make all
        run: |
          OCAMLRUNPARAM=b opam exec -- make all -B
