# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-nix-21-05:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - run: nix-build release.nix
    - run: nix-shell --run "echo OK"

  build-nix-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build release.nix
    - run: nix-shell --run "echo OK"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11.x
          dune-cache: true

      - name: Install Python dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python3-pygments man2html rsync colordiff libmpc-dev
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install virtualenv
          sudo make pygments
          ./french_law/python/setup_env.sh

      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only --with-doc --with-test

      - name: Make all
        run: |
          OCAMLRUNPARAM=b opam exec -- make all
