name: FullBuildCI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-nix-21-05:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

  build-nix-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

