name: Builds

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v15
      - run: nix develop -c echo ok
      - run: nix build
      - run: nix build .#clerk
