name: Harness

on:
  push:
    branches: [master]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-make-all:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Re-initialize python dependencies
        run: |
          rm -rf french_law/python/env
          ./french_law/python/setup_env.sh
      - name: Make all
        run: |
          OCAMLRUNPARAM=b opam exec -- make dependencies all -B
