name: Builds

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11.x
          dune-cache: true

      - name: Install external dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-dev virtualenv python3-setuptools python3-pip python3-pygments man2html rsync colordiff npm nodejs libmpc-dev ninja-build
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install virtualenv
          sudo make pygments
          ./french_law/python/setup_env.sh
      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only --with-doc --with-test
      - name: Make build
        run: |
          OCAMLRUNPARAM=b opam exec -- make build

  build-nix-21-05:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

  build-nix-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: nix-build release.nix
      - run: nix-shell --run "echo OK"

